version: '1.0'
services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-localhost}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
    configSchema:
      type: "object"
      properties:
        mysql_host:
          type: "string"
          description: "MySQL server host"
          default: "localhost"
        mysql_port:
          type: "integer"
          description: "MySQL server port"
          default: 3306
        mysql_user:
          type: "string"
          description: "MySQL user"
        mysql_password:
          type: "string"
          description: "MySQL password"
          format: "password"
      required: ["mysql_user", "mysql_password"]
    startCommand:
      type: "stdio"
      commandFunction: |
        function getCommand(config) {
          return {
            command: "python3",
            args: ["mcp_server.py"],
            env: {
              "MYSQL_HOST": config.mysql_host || "localhost",
              "MYSQL_PORT": String(config.mysql_port || 3306),
              "MYSQL_USER": config.mysql_user,
              "MYSQL_PASSWORD": config.mysql_password
            }
          };
        } 